RENAMED_COLS = {
    "total_points": "points",
    "minutes": "mins",
    "goals_scored": "goals",
    "clean_sheets": "cs",
    "goals_conceded": "gc",
    "own_goals": "og",
    "penalties_saved": "ps",
    "penalties_missed": "pm",
    "yellow_cards": "yc",
    "red_cards": "rc",
    "influence": "i",
    "creativity": "c",
    "threat": "t",
    "ict_index": "ict",
    "expected_goals": "xG",
    "expected_assists": "xA",
    "expected_goal_involvements": "xGI",
    "expected_goals_conceded": "xGC",
}

BASE_FEATURES = [
    "assists_fpf", "bps_fpf", "cs_fpf", "c_fpf", "xA_fpf", "xGI_fpf",
    "xG_fpf", "xGC_fpf", "gc_fpf", "goals_fpf", "ict_fpf", "i_fpf",
    "mins_fpf", "og_fpf", "pm_fpf", "ps_fpf", "rc_fpf", "saves_fpf",
    "t_fpf", "points_fpf", "prop_mins_fpf",
    "ave_points_fpf", "ave_assists_fpf", "ave_goals_fpf", "ave_cs_fpf",
    "ave_xA_fpf", "ave_xGI_fpf", "ave_xG_fpf", "ave_bps_fpf",
    "ave_xGC_fpf", "ave_i_fpf", "ave_c_fpf", "ave_t_fpf",
    "ave_ict_fpf", "ave_saves_fpf", "ave_ps_fpf", "ave_yc_fpf",
    "ave_rc_fpf", "ave_mins_fpf",
    "ave_team_goals_fpf", "ave_team_xG_fpf", "ave_team_xA_fpf",
    "transfers_balance", "transfers_in", "transfers_out",
    "team_str", "team_str_h", "team_str_a",
    "team_str_att_h", "team_str_att_a",
    "team_str_def_h", "team_str_def_a",
    "oppo_str", "oppo_str_h", "oppo_str_a",
    "oppo_str_att_h", "oppo_str_att_a",
    "oppo_str_def_h", "oppo_str_def_a",
    "oppo_difficulty",
    "position_DEF", "position_FWD", "position_GKP", "position_MID",
]